#! /bin/zsh

set -e
echo "🔄 Checking if branch is up to date..."

git fetch origin

echo "🔍 Linting..."
deno lint

echo "🧪 Running tests..."
deno test -A

echo "Checking unused exports"
deno run -A find-unused-exports